using System.Xml.Serialization;

namespace Slices.V1.StandardConverters.DataCite;

#pragma warning disable RCS1036 // Remove unnecessary blank line.

#nullable disable

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
[XmlRoot(Namespace = "http://datacite.org/schema/kernel-4", IsNullable = false)]
public partial class resource
{

    
    public resourceIdentifier identifier { get; set; }

    
    [XmlArrayItem("creator", IsNullable = false)]
    public resourceCreator[] creators { get; set; }

    
    [XmlArrayItem("title", IsNullable = false)]
    public resourceTitle[] titles { get; set; }

    
    public resourcePublisher publisher { get; set; }

    
    [XmlElement(DataType = "token")]
    public string publicationYear { get; set; }

    
    public resourceResourceType resourceType { get; set; }

    
    [XmlArrayItem("subject", IsNullable = false)]
    public resourceSubject[] subjects { get; set; }

    
    [XmlArrayItem("contributor", IsNullable = false)]
    public resourceContributor[] contributors { get; set; }

    
    [XmlArrayItem("date", IsNullable = false)]
    public resourceDate[] dates { get; set; }

    
    [XmlElement(DataType = "language")]
    public string language { get; set; }

    
    [XmlArrayItem("alternateIdentifier", IsNullable = false)]
    public resourceAlternateIdentifier[] alternateIdentifiers { get; set; }

    
    [XmlArrayItem("relatedIdentifier", IsNullable = false)]
    public resourceRelatedIdentifier[] relatedIdentifiers { get; set; }

    
    [XmlArrayItem("size", IsNullable = false)]
    public string[] sizes { get; set; }


    [XmlArrayItem("format", IsNullable = false)]
    public string[] formats { get; set; }


    public string version { get; set; }

    
    [XmlArrayItem("rights", IsNullable = false)]
    public resourceRights[] rightsList { get; set; }

    
    [XmlArrayItem("description", IsNullable = false)]
    public resourceDescription[] descriptions { get; set; }

    
    [XmlArrayItem("geoLocation", IsNullable = false)]
    [XmlArrayItem("geoLocationBox", typeof(box), IsNullable = false, NestingLevel = 1)]
    [XmlArrayItem("geoLocationPlace", IsNullable = false, NestingLevel = 1)]
    [XmlArrayItem("geoLocationPoint", typeof(point), IsNullable = false, NestingLevel = 1)]
    [XmlArrayItem("geoLocationPolygon", typeof(resourceGeoLocationGeoLocationPolygon), IsNullable = false, NestingLevel = 1)]
    public object[][] geoLocations { get; set; }


    [XmlArrayItem("fundingReference", IsNullable = false)]
    public resourceFundingReference[] fundingReferences { get; set; }
}


[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceIdentifier
{


    [XmlAttribute]
    public string identifierType { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public partial class box
{


    public float westBoundLongitude { get; set; }


    public float eastBoundLongitude { get; set; }


    public float southBoundLatitude { get; set; }


    public float northBoundLatitude { get; set; }
}



[Serializable]


[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public partial class point
{


    public float pointLongitude { get; set; }


    public float pointLatitude { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceCreator
{


    public resourceCreatorCreatorName creatorName { get; set; }


    public object givenName { get; set; }


    public object familyName { get; set; }


    [XmlElement("nameIdentifier")]
    public object[] nameIdentifier { get; set; }


    [XmlElement("affiliation")]
    public object[] affiliation { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceCreatorCreatorName
{


    [XmlAttribute]
    public nameType nameType { get; set; }


    [XmlIgnore]
    public bool nameTypeSpecified { get; set; }


    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum nameType
{

    
    Organizational,

    
    Personal,
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceTitle
{


    [XmlAttribute]
    public titleType titleType { get; set; }


    [XmlIgnore]
    public bool titleTypeSpecified { get; set; }


    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum titleType
{

    
    AlternativeTitle,

    
    Subtitle,

    
    TranslatedTitle,

    
    Other,
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourcePublisher
{


    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceResourceType
{


    [XmlAttribute]
    public resourceType resourceTypeGeneral { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum resourceType
{

    
    Audiovisual,

    
    Collection,

    
    DataPaper,

    
    Dataset,

    
    Event,

    
    Image,

    
    InteractiveResource,

    
    Model,

    
    PhysicalObject,

    
    Service,

    
    Software,

    
    Sound,

    
    Text,

    
    Workflow,

    
    Other,
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceSubject
{


    [XmlAttribute]
    public string subjectScheme { get; set; }


    [XmlAttribute(DataType = "anyURI")]
    public string schemeURI { get; set; }


    [XmlAttribute(DataType = "anyURI")]
    public string valueURI { get; set; }


    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceContributor
{


    public resourceContributorContributorName contributorName { get; set; }


    public object givenName { get; set; }


    public object familyName { get; set; }


    [XmlElement("nameIdentifier")]
    public object[] nameIdentifier { get; set; }


    [XmlElement("affiliation")]
    public object[] affiliation { get; set; }


    [XmlAttribute]
    public contributorType contributorType { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceContributorContributorName
{


    [XmlAttribute]
    public nameType nameType { get; set; }


    [XmlIgnore]
    public bool nameTypeSpecified { get; set; }


    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum contributorType
{

    
    ContactPerson,

    
    DataCollector,

    
    DataCurator,

    
    DataManager,

    
    Distributor,

    
    Editor,

    
    HostingInstitution,

    
    Other,

    
    Producer,

    
    ProjectLeader,

    
    ProjectManager,

    
    ProjectMember,

    
    RegistrationAgency,

    
    RegistrationAuthority,

    
    RelatedPerson,

    
    ResearchGroup,

    
    RightsHolder,

    
    Researcher,

    
    Sponsor,

    
    Supervisor,

    
    WorkPackageLeader,
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceDate
{


    [XmlAttribute]
    public dateType dateType { get; set; }


    [XmlAttribute]
    public string dateInformation { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum dateType
{

    
    Accepted,

    
    Available,

    
    Collected,

    
    Copyrighted,

    
    Created,

    
    Issued,

    
    Other,

    
    Submitted,

    
    Updated,

    
    Valid,

    
    Withdrawn,
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceAlternateIdentifier
{


    [XmlAttribute]
    public string alternateIdentifierType { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceRelatedIdentifier
{


    [XmlAttribute]
    public resourceType resourceTypeGeneral { get; set; }


    [XmlIgnore]
    public bool resourceTypeGeneralSpecified { get; set; }


    [XmlAttribute]
    public relatedIdentifierType relatedIdentifierType { get; set; }


    [XmlAttribute]
    public relationType relationType { get; set; }


    [XmlAttribute]
    public string relatedMetadataScheme { get; set; }


    [XmlAttribute(DataType = "anyURI")]
    public string schemeURI { get; set; }


    [XmlAttribute]
    public string schemeType { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum relatedIdentifierType
{

    
    ARK,

    
    arXiv,

    
    bibcode,

    
    DOI,

    
    EAN13,

    
    EISSN,

    
    Handle,

    
    IGSN,

    
    ISBN,

    
    ISSN,

    
    ISTC,

    
    LISSN,

    
    LSID,

    
    PMID,

    
    PURL,

    
    UPC,

    
    URL,

    
    URN,

    
    w3id,
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum relationType
{

    
    IsCitedBy,

    
    Cites,

    
    IsSupplementTo,

    
    IsSupplementedBy,

    
    IsContinuedBy,

    
    Continues,

    
    IsNewVersionOf,

    
    IsPreviousVersionOf,

    
    IsPartOf,

    
    HasPart,

    
    IsReferencedBy,

    
    References,

    
    IsDocumentedBy,

    
    Documents,

    
    IsCompiledBy,

    
    Compiles,

    
    IsVariantFormOf,

    
    IsOriginalFormOf,

    
    IsIdenticalTo,

    
    HasMetadata,

    
    IsMetadataFor,

    
    Reviews,

    
    IsReviewedBy,

    
    IsDerivedFrom,

    
    IsSourceOf,

    
    Describes,

    
    IsDescribedBy,

    
    HasVersion,

    
    IsVersionOf,

    
    Requires,

    
    IsRequiredBy,

    
    Obsoletes,

    
    IsObsoletedBy,
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceRights
{


    [XmlAttribute(DataType = "anyURI")]
    public string rightsURI { get; set; }


    [XmlAttribute]
    public string rightsIdentifier { get; set; }


    [XmlAttribute]
    public string rightsIdentifierScheme { get; set; }


    [XmlAttribute(DataType = "anyURI")]
    public string schemeURI { get; set; }


    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceDescription
{


    [XmlElement("br")]
    public resourceDescriptionBR[] Items { get; set; }


    [XmlText]
    public string[] Text { get; set; }


    [XmlAttribute]
    public descriptionType descriptionType { get; set; }


    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceDescriptionBR
{
}


[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum descriptionType
{

    
    Abstract,

    
    Methods,

    
    SeriesInformation,

    
    TableOfContents,

    
    TechnicalInfo,

    
    Other,
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceGeoLocationGeoLocationPolygon
{


    [XmlElement("polygonPoint")]
    public point[] polygonPoint { get; set; }


    public point inPolygonPoint { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceFundingReference
{


    public string funderName { get; set; }


    public resourceFundingReferenceFunderIdentifier funderIdentifier { get; set; }


    public resourceFundingReferenceAwardNumber awardNumber { get; set; }


    public object awardTitle { get; set; }
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceFundingReferenceFunderIdentifier
{


    [XmlAttribute]
    public funderIdentifierType funderIdentifierType { get; set; }


    [XmlAttribute(DataType = "anyURI")]
    public string schemeURI { get; set; }


    [XmlText]
    public string Value { get; set; }
}



[Serializable]
[XmlType(Namespace = "http://datacite.org/schema/kernel-4")]
public enum funderIdentifierType
{

    
    ISNI,

    
    GRID,

    
    ROR,

    
    [XmlEnum("Crossref Funder ID")]
    CrossrefFunderID,

    
    Other,
}



[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://datacite.org/schema/kernel-4")]
public partial class resourceFundingReferenceAwardNumber
{


    [XmlAttribute(DataType = "anyURI")]
    public string awardURI { get; set; }


    [XmlText]
    public string Value { get; set; }
}


#nullable restore

#pragma warning restore RCS1036 // Remove unnecessary blank line.
