using Slices.V1.StandardAnnotations;

namespace Slices.V1.Format;

// TODO: String length
// TODO: Optional lists

public sealed class DigitalObject
{
    #region Primary

    // TODO: Better type
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 1)]
    [SlicesParticipation(SlicesParticipationType.Required)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public string Identifier { get; set; } = null!;

    // TODO: Better type
    /// <summary>
    /// Internal Code created within SLICES which can be resolved by the SLICES portal.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 2)]
    [SlicesParticipation(SlicesParticipationType.Required)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public string InternalIdentifier { get; set; } = null!;

    /// <summary>
    /// An alternate identifier to the resource
    /// </summary>
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 3)]
    [SlicesParticipation(SlicesParticipationType.RequiredIfExists)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public string? AlternateIdentifier { get; set; }

    // TODO: Creators?
    /// <summary>
    /// The creator(s) of the digital object in priority order. May be a corporate/institutional or personal name.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 4)]
    [SlicesParticipation(SlicesParticipationType.Required)]
    [SlicesAccessModifer(SlicesAccessModiferType.PR)]
    public List<string> Creator { get; set; } = null!;

    // TODO: Better type
    // TODO: CreatorIdentifiers?
    /// <summary>
    /// Identifier(s) of the creator(s) of the digital object.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 5)]
    [SlicesParticipation(SlicesParticipationType.RequiredIfExists)]
    [SlicesAccessModifer(SlicesAccessModiferType.PR)]
    public List<string>? CreatorIdentifier { get; set; }

    /// <summary>
    /// A name or title by which a digital object is known.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 6)]
    [SlicesParticipation(SlicesParticipationType.Required)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public string Name { get; set; } = null!;

    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 7)]
    [SlicesParticipation(SlicesParticipationType.RequiredIfExists)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public string? Description { get; set; }

    // TODO: ResourceType

    /// <summary>
    /// The subject represented using key phrases, or classification codes. 
    /// </summary>
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 9)]
    [SlicesParticipation(SlicesParticipationType.Optional)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public List<string>? Subject { get; set; }

    /// <summary>
    /// An index term, subject term, subject heading, or descriptor, in information retrieval, is a term that captures the essence of the topic of a document.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 10)]
    [SlicesParticipation(SlicesParticipationType.Required)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public List<string> Keywords { get; set; } = null!;

    /// <summary>
    /// A timestamp generated by the system.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.PrimaryInformation, 11)]
    [SlicesParticipation(SlicesParticipationType.Required)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public DateTime DateTimeCreated { get; set; }

    #endregion Primary

    #region Management

    /// <summary>
    /// Version of the resource.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.ManagementInformation, 1)]
    [SlicesParticipation(SlicesParticipationType.Required)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public string Version { get; set; } = null!;

    // TODO: type
    /// <summary>
    /// The metadata profile used  to describe this  resource
    /// </summary>
    [SlicesCode(SlicesFieldCategory.ManagementInformation, 2)]
    [SlicesParticipation(SlicesParticipationType.Required)]
    [SlicesAccessModifer(SlicesAccessModiferType.PU)]
    public string MetadataProfile { get; set; } = null!;

    /// <summary>
    /// The institution or person responsible for collecting, managing, distributing, or otherwise contributing
    /// to the development of the digital object. Examples of cotributors are chair, contact group, contact person,
    /// contact for access. data collector, data curator,data manager, distributor, editor. funder. hosting institution.
    /// maintainer, producer, project leader, project manager, project member, provider, publisher, reader,
    /// registration agency, registration authority, related person, researcher, research group, review assistant,
    /// reviewer, reviewer-external, rights holder, sponsor, stats-reviewer, supervisor, translator, workpackage leader.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.ManagementInformation, 3)]
    [SlicesParticipation(SlicesParticipationType.RequiredIfExists)]
    [SlicesAccessModifer(SlicesAccessModiferType.PR)]
    public List<string>? Contributor { get; set; }

    /// <summary>
    /// Identifier(s) of the contributor(s) of the digital object.
    /// </summary>
    [SlicesCode(SlicesFieldCategory.ManagementInformation, 0)]
    [SlicesParticipation(SlicesParticipationType.RequiredIfExists)]
    [SlicesAccessModifer(SlicesAccessModiferType.PR)]
    public List<string>? ContributorIdentifier { get; set; }

    #endregion Management


    #region TypeSpecific

    public Software? Software { get; set; }

    // TODO

    #endregion TypeSpecific
}
